dat <- fread("external_data/paro_2018_ecd_ph_transcriptomes_metadata.txt")
dat <- dat[, .(ftp= unlist(strsplit(ftp, "\\|"))), experiment_title]
dat[, cdition:= unlist(tstrsplit(dat$experiment_title, ":|;", keep= 2))]
dat[, cdition:= gsub("^ Tumor_|^ ", "", cdition)]
dat[, cdition:= gsub("^Sph", "ecd", cdition)]
dat[, cdition:= gsub("Control", "WT", cdition)]
dat[, cdition:= paste0("RNA_", gsub("_", "ED_rep", cdition))]
dat[grepl("_1.fastq.gz$", ftp), fq:= paste0("db/fastq/RNA_Paro_2018/", cdition, "_1.fq.gz"), cdition]
dat[grepl("_2.fastq.gz$", ftp), fq:= paste0("db/fastq/RNA_Paro_2018/", cdition, "_2.fq.gz"), cdition]
dat[is.na(fq), fq:= paste0("db/fastq/RNA_Paro_2018/", cdition, ".fq.gz"), cdition]
dat[, if(!file.exists(fq)) download.file(ftp, fq) else print("DONE"), (dat)]
